### ISSUE TITLE
12h time without trailing zero

### ISSUE THREAD

**Issue by papioara** [GirkovArpa/temps-lite#20]
Yesterday I noticed that there is no trailing zero for minutes, when it is between hh:01 and hh:05 in 12h mode, but only there, and not in 24h mode.

**Comment by GirkovArpa** [comment]
Thanks for catching that, [fixed](https://github.com/GirkovArpa/temps-lite/commit/0cb42ad1becd6a7db34a15aa9d1f98f22ce92b91).

**Comment by GirkovArpa** [comment]
To be clear, you meant to `hh:09`, right?
