### ISSUE TITLE
lat, lon 

### ISSUE THREAD

**Issue by GirkovArpa** [GirkovArpa/temps-lite#21]
@papioara Since lat, lon input is supported now, shouldn't we update the readme to reflect that?

**Comment by papioara** [comment]
Yes, of course! Just to be sure I get this right: can you just enter LAT xx.xxxx, LON xx.xxx now instead of &lat=xx.xxxx&lon=xx.xxxx?

**Comment by GirkovArpa** [comment]
Right, except without the words LAT and LON, of course. Any 2 numbers, decimal or integer, separated by anything, will do.  Even `foo123.456,bar7` will be interpreted as `123.456`, `7`

**Comment by papioara** [comment]
Good! I have updated the Readme.md accordingly

**Comment by GirkovArpa** [comment]
Thank you!
