### ISSUE TITLE
Merge Rust repository with this one

### ISSUE THREAD

**Issue by GirkovArpa** [GirkovArpa/temps-lite#23]
> Should I update the Readme for the Linux users? Making the temps-lite autostart work is not complicated with concise instructions, but at the moment the option in the settings is useless, at least on Linux. At least there is a good workaround.

Well, I did have "autostart" in the "Todo" section 😄 

https://github.com/GirkovArpa/temps-lite#todo-

But @4silvertooth has added Linux autostart functionality with [this](https://github.com/GirkovArpa/temps-lite/commit/b977bb2327f797ec0b6ed1acd82f677ae96cfd9b) commit.  I've also added it for Windows [here](https://github.com/GirkovArpa/temps-lite-rust/commit/565d07f30e9a6ffe3780ef96b854fb4010f97101) but that is a different repository slightly reworked that can only be compiled with Rust, because I'm using native code to modify the Windows Registry.

I need to merge the two repositories but first I should ask, are you okay with having to run the program via Rust like `cargo run` (requiring the installation of Rust and whatever difficulties that may entail), or would you prefer that I try to restructure the program so that it can be tested both via Rust and via plain old scapp.exe (with limited functionality in the latter case)?

Of course the compiled binary will not require scapp or Rust.  I just don't want to introduce excessive complications when testing.

_Originally posted by @GirkovArpa in https://github.com/GirkovArpa/temps-lite/issues/17#issuecomment-786356849_

**Comment by 4silvertooth** [comment]
Hello, my commit assumes it's run with scapp on Linux to auto start on login to work, needs to change if it's `cargo build`.

**Comment by GirkovArpa** [comment]
I'd just need to change [this](https://github.com/GirkovArpa/temps-lite/commit/b977bb2327f797ec0b6ed1acd82f677ae96cfd9b#diff-8a1a972344a6c7b66381c2c16d59673cd84d6d70a2b9e6cf5800cf290f0c17e4R58) line from:
```javascript
const appPath = URL.toPath(self.url("./scapp"));
```
To this, right?
```javascript
const appPath = URL.toPath(self.url("./"));
```

**Comment by 4silvertooth** [comment]
const appPath = URL.toPath(self.url("./APPNAME"));

APPNAME = executable name produced by cargo build

**Comment by 4silvertooth** [comment]
I've made a commit to the rust repo, first time on rust so please verify, I've tested build on both on windows and linux with autostart working, but the checkbox needs a look, as after a new launch its unchecked even though it needs to be checked.

**Comment by papioara** [comment]
Yes, I can confirm this behaviour. Temps-lite places an entry in /.config/autostart when you have checked the option in the settings panel. When you click 'Apply', then 'Quit' and relaunch, the checkmark is gone, but the file in the autostart folder is there. This is of course confusing for the average user.

**Comment by 4silvertooth** [comment]
I've fixed that on the rust repo.
