### ISSUE TITLE
Missing translations for the word "Portuguese"

### ISSUE THREAD

**Issue by GirkovArpa** [GirkovArpa/temps-lite#28]
For example:

https://github.com/GirkovArpa/temps-lite/blob/423e7e02b4b901ebba4dc9ef967981ce1f4d43d9/locale/dutch.json#L19-L24

![screenshot](https://i.imgur.com/czRo7Bp.png)

**Comment by goliv04053** [comment]
I'm gonna fix it. A sec

**Comment by goliv04053** [comment]
Give a look if it's working.

**Comment by GirkovArpa** [comment]
Thank you, but a couple are still missing commas, and it will crash without them 🤷‍♂️ The Italian and Spanish ones, at least.

P.S. If you push all the changes to your fork, you can then make a single pull request of the entire fork!  This could save you the trouble of making many individual pull requests for each change 👍

**Comment by GirkovArpa** [comment]
Don't worry about it.  I will fix them when I get a chance.

**Comment by GirkovArpa** [comment]
[Fixed](https://github.com/GirkovArpa/temps-lite/commit/017c8da55a924cc43f58e3a7fbdb5bd8e5f01059)
