### ISSUE TITLE
Fonts on Linux

### ISSUE THREAD

**Issue by GirkovArpa** [GirkovArpa/temps-lite#3]
Hello again,

Hopefully the last one for today, but just for your info, if this tells you something. Launching scapp in the Terminal, I see these warnings:

(Temps-lite) BBB 05:03:42  $ scapp
warning:css: in @font-face statement, failed to install font at (file:///home/falter/Temps-lite/rubik.css(4))
warning:css: in @font-face statement, failed to install font at (file:///home/falter/Temps-lite/rubik.css(9))
warning:css: in @font-face statement, failed to install font at (file:///home/falter/Temps-lite/rubik.css(14))
warning:DOM: failed to load "/home/falter/Temps-lite/assets/iconTemplate@2x.png" file, error=2

(scapp:95456): GLib-CRITICAL **: 17:04:11.730: Source ID 805 was not found when attempting to remove it

(scapp:95456): GLib-CRITICAL **: 17:05:00.727: Source ID 3818 was not found when attempting to remove it

(scapp:95456): GLib-CRITICAL **: 17:07:55.156: Source ID 9473 was not found when attempting to remove it

(scapp:95456): GLib-CRITICAL **: 17:08:29.759: Source ID 16848 was not found when attempting to remove it

The file is in the assets folder, I have checked. Does it have something to do with rubik.css?

I'll send the modified files for French and Dutch later today

So long...

_Originally posted by @papioara in https://github.com/GirkovArpa/temps-lite/issues/1#issuecomment-774692348_

**Comment by GirkovArpa** [comment]
> warning:css: in @font-face statement, failed to install font at (file:///home/falter/Temps-lite/rubik.css(4))

Response from the creator of Sciter [here](https://sciter.com/forums/topic/linux-font-face-usage):
> At the moment sciter with Cairo backend (“on” by default) does not support in-memory fonts.
There is simply no official way of loading fonts from memory in Cairo/Pango on Linux.

Still, I will see about other ways of using the font.  Perhaps it is possible to install it manually on Linux?  

> (scapp:95456): GLib-CRITICAL **: 17:04:11.730: Source ID 805 was not found when attempting to remove it

Answer [here](https://stackoverflow.com/questions/23199699/glib-critical-source-id-xxx-was-not-found-when-attempting-to-remove-it/24057455#24057455):
> In most cases this is completely harmless, and only an annoyance.

**Comment by papioara** [comment]
[rubik.css.zip](https://github.com/GirkovArpa/temps-lite/files/5951237/rubik.css.zip)
Thanks!  I have experimented a bit and installed the Rubik font on my system. Then I changed the URLs in rubik.css. This does not seem to work, though, since now, I just get athe same error:

BBB 12:49:39  $ Bilder/temps-lite-master/scapp
warning:css: in @font-face statement, failed to install font at (file:///home/falter/Bilder/temps-lite-master/rubik.css(4))
warning:css: in @font-face statement, failed to install font at (file:///home/falter/Bilder/temps-lite-master/rubik.css(9))
warning:css: in @font-face statement, failed to install font at (file:///home/falter/Bilder/temps-lite-master/rubik.css(14))
warning:DOM: failed to load "/home/falter/Bilder/temps-lite-master/assets/iconTemplate@2x.png" file, error=2

Something absolutely insists on loading the fonts from /assets/fonts, but I cannot find it. Is there another file I would need to edit?

**Comment by papioara** [comment]
Edit: I does not matter obviously, what I put into rubik.css as a URL for the fonts. They are definitely installed on the system. Tried my word processor, and the Rubik font shows up in its font menu there.

**Comment by papioara** [comment]
Another small change with better wording in german.json
[german.json.zip](https://github.com/GirkovArpa/temps-lite/files/5954092/german.json.zip)

**Comment by GirkovArpa** [comment]
If you delete line 6 from `main.htm`, or comment it out like so, the error message should not be displayed:
```html
<!--<link href="rubik.css" rel="stylesheet">-->
```
This will cause it to ignore `rubik.css` (which can be deleted).  

Just to be sure, does the application now correctly use Rubik font, as compared to your previous screenshots?  I did the same on Windows, but of course it's no guarantee that it works on Linux.

> Another small change with better wording in german.json
> [german.json.zip](https://github.com/GirkovArpa/temps-lite/files/5954092/german.json.zip)

It might be more convenient for you to edit the file `german.json` directly:

![screenshot](https://i.imgur.com/ojkbm3X.png)

This will clone this repository onto your account.  After committing the change, you can then submit a "pull request" for me to merge your changes with this repository, or make further changes to the clone on your account before making the pull request.

This could possibly save you the trouble of downloading and uploading.

**Comment by papioara** [comment]
Hi,
as for the editing of the text files: will do what you proposed. Did not know it could be done like this. It's really more convenient. Thank you.
Here are two screenshots showing what temps-lite looks like with and without rubik.css:

![WithoutRubik css](https://user-images.githubusercontent.com/31970041/107578436-0715e600-6bf4-11eb-9b9d-cf5105d4a45c.png)

![WithRubik css](https://user-images.githubusercontent.com/31970041/107577342-9ae6b280-6bf2-11eb-84fc-774134790c27.png)

To me they look the same. 

And here is my terminal output first with, and then without rubik.css. There is only that one error left, but to me it seems that temps-lite complains (when rubik.css is on), but loads the font nevertheless, and it also looked the same, before I installed the Rubik font on my system.

(temps-lite-master) BBB 10:35:55  $ scapp
warning:css: in @font-face statement, failed to install font at (file:///home/falter/Bilder/temps-lite-master/rubik.css(4))
warning:css: in @font-face statement, failed to install font at (file:///home/falter/Bilder/temps-lite-master/rubik.css(9))
warning:css: in @font-face statement, failed to install font at (file:///home/falter/Bilder/temps-lite-master/rubik.css(14))
warning:DOM: failed to load "/home/falter/Bilder/temps-lite-master/assets/iconTemplate@2x.png" file, error=2

(scapp:398723): GLib-CRITICAL **: 22:36:26.968: Source ID 2039 was not found when attempting to remove it

(scapp:398723): GLib-CRITICAL **: 22:36:29.754: Source ID 2085 was not found when attempting to remove it

(scapp:398723): GLib-CRITICAL **: 22:36:57.160: Source ID 4734 was not found when attempting to remove it

(scapp:398723): GLib-CRITICAL **: 22:42:07.433: Source ID 5162 was not found when attempting to remove it

(scapp:398723): GLib-CRITICAL **: 22:43:19.573: Source ID 24844 was not found when attempting to remove it


 (temps-lite-master) BBB 10:45:13  $ scapp
warning:DOM: failed to load "/home/falter/Bilder/temps-lite-master/assets/iconTemplate@2x.png" file, error=2

(scapp:400718): GLib-CRITICAL **: 22:46:20.731: Source ID 3104 was not found when attempting to remove it

**Comment by GirkovArpa** [comment]
I believe the fonts are working on your system?  I cut out the time display from your [past screenshots](https://github.com/GirkovArpa/temps-lite/issues/1) (before installation) and current ones and compared them with mine:

![](https://i.imgur.com/QIWVrbs.png)

**Comment by GirkovArpa** [comment]
Assuming the font issue is resolved, I've closed this and branched the other issues into their own separate threads.
