### ISSUE TITLE
Time/Date Localization Issue

### ISSUE THREAD

**Issue by GirkovArpa** [GirkovArpa/temps-lite#4]
Crazy... See the two screenschots with your animation and my temps window next to each other. Weekdays and month names never change regardless of the language. Apply clicked, of course...
And the time is shown differently, too. It is different in 12 or 24h mode, but there is no AM or PM.
How do you launch temps-lite? Are you on Windows? Maybe it has something to do with the OS? Or is there another commit in the meantime?

![Auswahl_013](https://user-images.githubusercontent.com/31970041/107295637-10764580-6a70-11eb-895b-ec94c53e15a4.png)
![Auswahl_015](https://user-images.githubusercontent.com/31970041/107295647-153af980-6a70-11eb-9b39-49f981bc09b2.png)

_Originally posted by @papioara in https://github.com/GirkovArpa/temps-lite/issues/1#issuecomment-775543402_

**Comment by GirkovArpa** [comment]
I don't believe there's been another commit since then.  I'm in the USA on Windows and will try to figure this out.

**Update**

> [Implementation of arbitrary locale (the lang attribute value) is problematic for now – seems like Linix do not have full locales database by default anywhere.](https://sciter.com/forums/topic/does-sciter-support-date-format-attribute/#post-61243)

Since the current method of translating month and day names uses the `lang` attribute of a calendar input, this must be the issue.  I will find a way to support manual translations.

**Comment by papioara** [comment]
Great! Keep me updated. If you can manually enter translations, that would be great, since it never is a lot text, and it works well  with the LANGUAGE.json files.

**Comment by GirkovArpa** [comment]
I think I fixed all the translation issues with the latest update, here is how it looks on my computer at least:

![screenshot](https://i.imgur.com/J81bHD0.gif)

All that remains is to fix the the lack of AM/PM display for your timezone/OS.

And the Italian "Avete bisgono ...", which is so long it pushes the copyright notice off the edge:

![screenshot2](https://i.imgur.com/0L7pAY9.png)

**Comment by GirkovArpa** [comment]
Line-break issue solved with [this](https://github.com/GirkovArpa/temps-lite/pull/5) pull request.  Moved the AM/PM issue to their own thread.  Hopefully breaking these issue threads up makes things simpler not more complex 😄
