### ISSUE TITLE
failed to load iconTemplate@2x.png

### ISSUE THREAD

**Issue by GirkovArpa** [GirkovArpa/temps-lite#6]
warning:DOM: failed to load "/home/falter/Bilder/temps-lite-master/assets/iconTemplate@2x.png" file, error=2

_Originally posted by @papioara in https://github.com/GirkovArpa/temps-lite/issues/3#issuecomment-777063350_

**Comment by GirkovArpa** [comment]
Does this spinning, tiny sun in [this](https://github.com/GirkovArpa/temps-lite/raw/master/preview.gif) screenshot not display?

I assume that's because of the `@` in the filename, although I'm unable to find [any source](https://unix.stackexchange.com/a/377349) confirming this is an issue on Linux.

In any case, I believe it's worth trying to remove the `@` in line `90` in [main.htm](https://github.com/GirkovArpa/temps-lite/blob/master/main.htm#L90):

```html
<img #spinner src="assets/iconTemplate@2x.png" />
```
And removing the `@` from the filename of [iconTemplate@2x.png](https://github.com/GirkovArpa/temps-lite/blob/master/assets/IconTemplate%402x.png).

**Comment by papioara** [comment]
No, no spinning sun, but a spinning something - also nice - instead. Renaming the icon by removing the @ and changing the line in main.htm leads to the same complaint, only without the @ in the file name. Somehow temps-lite cannot load it, but it does not say what's wrong with it.

**Comment by GirkovArpa** [comment]
Presumably fixed by your typo-correction [here](https://github.com/GirkovArpa/temps-lite/pull/9)?
