### ISSUE TITLE
AM/PM not shown

### ISSUE THREAD

**Issue by GirkovArpa** [GirkovArpa/temps-lite#8]
And the time is shown differently, too. It is different in 12 or 24h mode, but there is no AM or PM.

_Originally posted by @papioara in https://github.com/GirkovArpa/temps-lite/issues/1#issuecomment-775543402_

**Comment by papioara** [comment]
With almost everything fixed now: Do you have any ideas how to go about the 12h/24h issue?

**Comment by papioara** [comment]
Just discovered another glitch: temps-lite shows the wrong date. It is already Monday, Feb 15 in Germany since 23 minutes now, see screenshot taken just now.

![WrongDate](https://user-images.githubusercontent.com/31970041/107892261-4d38b580-6f24-11eb-82ac-b2f13b63d9b1.png)

**Comment by GirkovArpa** [comment]
Timezone should be fixed with [latest commit](https://github.com/GirkovArpa/temps-lite/commit/b6b30b94ab6e0ce766516defb05a7d9589785d5a). It was using UTC time, so I shifted it to local time.  At least it seems to work here now, because I had the same problem.

Will investigate the AM/PM issue soon.

**Update**

Waiting on response [here](https://sciter.com/forums/topic/tis-time-manipulation/#post-69884).  Might end up having to do some math if it's not supported natively.

**Comment by GirkovArpa** [comment]
I believe it's been fixed with [this commit](https://github.com/GirkovArpa/temps-lite/commit/39a82839b71df4ece1860d1bbb182f820d8f7bd1).

**Comment by papioara** [comment]
Confirmation: I tested it, and it works now. Wonderful! Thanks a lot!
